-- NightStory — Scenes column migration
-- Run in: Supabase Dashboard → SQL Editor → New query → Run
--
-- Adds the `scenes` JSONB column to stories and trash so that
-- scene metadata generated by produce-drama is persisted.
-- Safe to re-run (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).

ALTER TABLE public.stories
  ADD COLUMN IF NOT EXISTS scenes jsonb;

ALTER TABLE public.trash
  ADD COLUMN IF NOT EXISTS scenes jsonb;
